import { Session, Speaker, AgendaItem, Attendee } from '@/types';

export const speakers: Speaker[] = [
  {
    id: 'sp1',
    name: 'Sarah Chen',
    role: 'VP of Engineering',
    company: 'NeuralTech AI',
    bio: 'Sarah is a pioneer in production AI systems with over 15 years of experience deploying machine learning at scale. She has led engineering teams at Google Brain, OpenAI, and now NeuralTech AI, where she oversees a team of 200+ engineers building next-generation AI infrastructure.',
    topics: ['AI/ML', 'Production Systems', 'MLOps'],
    sessions: ['The Future of AI in Production', 'MLOps Best Practices Workshop'],
    isKeynote: true,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
    website: 'https://sarahchen.dev',
  },
  {
    id: 'sp2',
    name: 'Marcus Johnson',
    role: 'Principal Architect',
    company: 'CloudScale Inc.',
    bio: 'Marcus specializes in distributed systems and cloud-native architectures. He has designed infrastructure for companies serving billions of requests per day and is a frequent contributor to CNCF projects.',
    topics: ['Cloud Native', 'Kubernetes', 'Distributed Systems'],
    sessions: ['Scaling to a Billion Requests', 'Kubernetes at the Edge'],
    isKeynote: false,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'sp3',
    name: 'Priya Patel',
    role: 'Security Research Lead',
    company: 'CyberShield Labs',
    bio: 'Priya is a renowned cybersecurity expert who has discovered critical vulnerabilities in major cloud platforms. She leads a team of security researchers and regularly presents at DEF CON and Black Hat.',
    topics: ['Security', 'Zero Trust', 'Threat Intelligence'],
    sessions: ['Zero Trust Architecture in 2024', 'Supply Chain Security'],
    isKeynote: true,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'sp4',
    name: 'David Kim',
    role: 'Staff Engineer',
    company: 'Meta',
    bio: 'David works on React and the broader JavaScript ecosystem at Meta. He is a core contributor to React and has been instrumental in developing React Server Components and the new React compiler.',
    topics: ['React', 'JavaScript', 'Web Performance'],
    sessions: ['React in 2024: What\'s Next', 'Web Performance Deep Dive'],
    isKeynote: false,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
    website: 'https://davidkim.dev',
  },
  {
    id: 'sp5',
    name: 'Aisha Okonkwo',
    role: 'CTO',
    company: 'DevFlow',
    bio: 'Aisha founded DevFlow, a developer productivity platform used by 50,000+ teams. She is passionate about developer experience and has written extensively about platform engineering and internal developer portals.',
    topics: ['Platform Engineering', 'DevEx', 'Developer Tools'],
    sessions: ['Building Internal Developer Platforms', 'The Future of DevEx'],
    isKeynote: false,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'sp6',
    name: 'Raj Sharma',
    role: 'Distinguished Engineer',
    company: 'Amazon Web Services',
    bio: 'Raj has been at AWS for 12 years and has led the development of several core services including Lambda, Step Functions, and EventBridge. He is a thought leader in serverless architecture.',
    topics: ['Serverless', 'AWS', 'Event-Driven Architecture'],
    sessions: ['Serverless at Scale', 'Event-Driven Microservices'],
    isKeynote: false,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'sp7',
    name: 'Elena Vasquez',
    role: 'Head of Mobile',
    company: 'Spotify',
    bio: 'Elena leads mobile engineering at Spotify, overseeing apps used by 600M+ users. She is an expert in cross-platform development, mobile performance optimization, and large-scale app architecture.',
    topics: ['Mobile', 'React Native', 'iOS/Android'],
    sessions: ['Mobile at Spotify Scale', 'Cross-Platform Architecture Patterns'],
    isKeynote: false,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'sp8',
    name: 'Tom Nakamura',
    role: 'Open Source Lead',
    company: 'Vercel',
    bio: 'Tom maintains Next.js and several other popular open source projects at Vercel. He has contributed to the web platform and is passionate about making the web faster and more accessible for everyone.',
    topics: ['Next.js', 'Open Source', 'Web Platform'],
    sessions: ['Next.js 15 and Beyond', 'The Edge Computing Revolution'],
    isKeynote: false,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
    website: 'https://tomnakamura.dev',
  },
];

export const sessions: Session[] = [
  {
    id: 'sess1',
    title: 'The Future of AI in Production: Lessons from 10 Billion Inferences',
    description: 'Sarah shares hard-won lessons from deploying AI models at massive scale, covering model serving, cost optimization, latency reduction, and the organizational challenges of running AI in production.',
    speaker: { id: 'sp1', name: 'Sarah Chen', role: 'VP of Engineering', company: 'NeuralTech AI' },
    track: 'AI & ML',
    type: 'Keynote',
    time: '9:00 AM',
    duration: '45 min',
    day: 'Day 2 — June 13',
    dayId: 'day2',
    room: 'Main Stage',
    attendeeCount: 2847,
    isLive: true,
    featured: true,
    tags: ['AI', 'Production', 'Scale', 'MLOps'],
  },
  {
    id: 'sess2',
    title: 'React in 2024: Server Components, the New Compiler, and What\'s Next',
    description: 'A deep dive into the latest React features including Server Components, the new React compiler, and the roadmap for React 19. Learn how these changes will fundamentally shift how we build web applications.',
    speaker: { id: 'sp4', name: 'David Kim', role: 'Staff Engineer', company: 'Meta' },
    track: 'Web Dev',
    type: 'Talk',
    time: '10:30 AM',
    duration: '40 min',
    day: 'Day 1 — June 12',
    dayId: 'day1',
    room: 'Web Track',
    attendeeCount: 1923,
    isLive: false,
    featured: true,
    tags: ['React', 'JavaScript', 'Frontend'],
  },
  {
    id: 'sess3',
    title: 'Zero Trust Architecture: Securing Modern Cloud Infrastructure',
    description: 'Priya walks through implementing zero trust security from the ground up, covering identity-based access, micro-segmentation, continuous verification, and real-world case studies from Fortune 500 companies.',
    speaker: { id: 'sp3', name: 'Priya Patel', role: 'Security Research Lead', company: 'CyberShield Labs' },
    track: 'Security',
    type: 'Talk',
    time: '2:00 PM',
    duration: '40 min',
    day: 'Day 3 — June 14',
    dayId: 'day3',
    room: 'Security Track',
    attendeeCount: 1456,
    isLive: false,
    featured: true,
    tags: ['Security', 'Zero Trust', 'Cloud'],
  },
  {
    id: 'sess4',
    title: 'Scaling Kubernetes to 100,000 Nodes: A CloudScale Story',
    description: 'Marcus shares the journey of scaling Kubernetes clusters to unprecedented sizes, the custom operators built, the failures encountered, and the architectural decisions that made it possible.',
    speaker: { id: 'sp2', name: 'Marcus Johnson', role: 'Principal Architect', company: 'CloudScale Inc.' },
    track: 'DevOps',
    type: 'Talk',
    time: '11:30 AM',
    duration: '40 min',
    day: 'Day 1 — June 12',
    dayId: 'day1',
    room: 'DevOps Track',
    attendeeCount: 1234,
    isLive: false,
    featured: false,
    tags: ['Kubernetes', 'DevOps', 'Scale'],
  },
  {
    id: 'sess5',
    title: 'Serverless at Scale: Building Event-Driven Systems with AWS Lambda',
    description: 'Raj explores advanced patterns for serverless architectures, including fan-out/fan-in patterns, saga orchestration, and how to handle the operational challenges of running thousands of Lambda functions.',
    speaker: { id: 'sp6', name: 'Raj Sharma', role: 'Distinguished Engineer', company: 'Amazon Web Services' },
    track: 'Cloud',
    type: 'Talk',
    time: '3:00 PM',
    duration: '40 min',
    day: 'Day 2 — June 13',
    dayId: 'day2',
    room: 'Cloud Track',
    attendeeCount: 987,
    isLive: false,
    featured: false,
    tags: ['Serverless', 'AWS', 'Lambda'],
  },
  {
    id: 'sess6',
    title: 'Building Internal Developer Platforms That Developers Actually Love',
    description: 'Aisha shares the principles behind DevFlow\'s success in building developer tooling, covering the golden path concept, self-service infrastructure, and how to measure developer productivity.',
    speaker: { id: 'sp5', name: 'Aisha Okonkwo', role: 'CTO', company: 'DevFlow' },
    track: 'DevOps',
    type: 'Talk',
    time: '1:00 PM',
    duration: '40 min',
    day: 'Day 1 — June 12',
    dayId: 'day1',
    room: 'DevOps Track',
    attendeeCount: 1102,
    isLive: false,
    featured: true,
    tags: ['Platform Engineering', 'DevEx', 'Productivity'],
  },
  {
    id: 'sess7',
    title: 'Mobile Engineering at Spotify: Serving 600M Users',
    description: 'Elena reveals the architecture behind Spotify\'s mobile apps, including their approach to offline-first design, A/B testing at scale, and how they manage releases across iOS and Android simultaneously.',
    speaker: { id: 'sp7', name: 'Elena Vasquez', role: 'Head of Mobile', company: 'Spotify' },
    track: 'Mobile',
    type: 'Talk',
    time: '2:30 PM',
    duration: '40 min',
    day: 'Day 2 — June 13',
    dayId: 'day2',
    room: 'Mobile Track',
    attendeeCount: 876,
    isLive: false,
    featured: false,
    tags: ['Mobile', 'iOS', 'Android', 'Scale'],
  },
  {
    id: 'sess8',
    title: 'Next.js 15 and the Edge Computing Revolution',
    description: 'Tom presents the latest Next.js features, the vision for edge-first web development, and how Vercel is pushing the boundaries of what\'s possible with server-side rendering at the edge.',
    speaker: { id: 'sp8', name: 'Tom Nakamura', role: 'Open Source Lead', company: 'Vercel' },
    track: 'Web Dev',
    type: 'Talk',
    time: '4:00 PM',
    duration: '40 min',
    day: 'Day 1 — June 12',
    dayId: 'day1',
    room: 'Web Track',
    attendeeCount: 2103,
    isLive: false,
    featured: true,
    tags: ['Next.js', 'Edge', 'Web'],
  },
];

export const agendaItems: AgendaItem[] = [
  // Day 1
  {
    id: 'ag1',
    title: 'Registration & Welcome Coffee',
    type: 'break',
    timeSlot: '8:00 AM',
    duration: '60 min',
    room: 'Virtual Lobby',
    dayId: 'day1',
    description: 'Get settled in, explore the platform, and connect with fellow attendees in the networking lounge.',
  },
  {
    id: 'ag2',
    title: 'Opening Keynote: The Developer in 2024',
    type: 'keynote',
    timeSlot: '9:00 AM',
    duration: '60 min',
    room: 'Main Stage',
    speaker: 'David Kim',
    track: 'Web Dev',
    dayId: 'day1',
    description: 'An inspiring look at how the developer landscape has transformed and where we are headed.',
  },
  {
    id: 'ag3',
    title: 'React in 2024: Server Components & the New Compiler',
    type: 'talk',
    timeSlot: '10:30 AM',
    duration: '40 min',
    room: 'Web Track',
    speaker: 'David Kim',
    track: 'Web Dev',
    dayId: 'day1',
    description: 'Deep dive into React Server Components and the new React compiler.',
  },
  {
    id: 'ag4',
    title: 'Scaling Kubernetes to 100,000 Nodes',
    type: 'talk',
    timeSlot: '11:30 AM',
    duration: '40 min',
    room: 'DevOps Track',
    speaker: 'Marcus Johnson',
    track: 'DevOps',
    dayId: 'day1',
    description: 'The journey of scaling Kubernetes clusters to unprecedented sizes.',
  },
  {
    id: 'ag5',
    title: 'Lunch Break & Networking',
    type: 'break',
    timeSlot: '12:30 PM',
    duration: '60 min',
    room: 'Networking Lounge',
    dayId: 'day1',
    description: 'Grab lunch and connect with other attendees in the virtual networking rooms.',
  },
  {
    id: 'ag6',
    title: 'Building Internal Developer Platforms',
    type: 'talk',
    timeSlot: '1:00 PM',
    duration: '40 min',
    room: 'DevOps Track',
    speaker: 'Aisha Okonkwo',
    track: 'DevOps',
    dayId: 'day1',
    description: 'Principles behind building developer tooling that developers actually love.',
  },
  {
    id: 'ag7',
    title: 'Next.js 15 and the Edge Computing Revolution',
    type: 'talk',
    timeSlot: '4:00 PM',
    duration: '40 min',
    room: 'Web Track',
    speaker: 'Tom Nakamura',
    track: 'Web Dev',
    dayId: 'day1',
    description: 'Latest Next.js features and the vision for edge-first web development.',
  },
  // Day 2
  {
    id: 'ag8',
    title: 'The Future of AI in Production',
    type: 'keynote',
    timeSlot: '9:00 AM',
    duration: '45 min',
    room: 'Main Stage',
    speaker: 'Sarah Chen',
    track: 'AI & ML',
    dayId: 'day2',
    isLive: true,
    description: 'Lessons from deploying AI models at massive scale.',
  },
  {
    id: 'ag9',
    title: 'MLOps Best Practices Workshop',
    type: 'workshop',
    timeSlot: '10:30 AM',
    duration: '90 min',
    room: 'Workshop Room A',
    speaker: 'Sarah Chen',
    track: 'AI & ML',
    dayId: 'day2',
    description: 'Hands-on workshop covering MLOps pipelines, model monitoring, and deployment strategies.',
  },
  {
    id: 'ag10',
    title: 'Serverless at Scale: AWS Lambda Patterns',
    type: 'talk',
    timeSlot: '3:00 PM',
    duration: '40 min',
    room: 'Cloud Track',
    speaker: 'Raj Sharma',
    track: 'Cloud',
    dayId: 'day2',
    description: 'Advanced patterns for serverless architectures at scale.',
  },
  {
    id: 'ag11',
    title: 'Mobile Engineering at Spotify',
    type: 'talk',
    timeSlot: '2:30 PM',
    duration: '40 min',
    room: 'Mobile Track',
    speaker: 'Elena Vasquez',
    track: 'Mobile',
    dayId: 'day2',
    description: 'Architecture behind Spotify\'s mobile apps serving 600M users.',
  },
  // Day 3
  {
    id: 'ag12',
    title: 'Zero Trust Architecture Keynote',
    type: 'keynote',
    timeSlot: '9:00 AM',
    duration: '45 min',
    room: 'Main Stage',
    speaker: 'Priya Patel',
    track: 'Security',
    dayId: 'day3',
    description: 'The state of security in 2024 and the zero trust imperative.',
  },
  {
    id: 'ag13',
    title: 'Zero Trust Architecture: Securing Modern Cloud Infrastructure',
    type: 'talk',
    timeSlot: '2:00 PM',
    duration: '40 min',
    room: 'Security Track',
    speaker: 'Priya Patel',
    track: 'Security',
    dayId: 'day3',
    description: 'Implementing zero trust security from the ground up.',
  },
  {
    id: 'ag14',
    title: 'Closing Panel: The Future of Software Development',
    type: 'panel',
    timeSlot: '4:30 PM',
    duration: '60 min',
    room: 'Main Stage',
    speaker: 'All Keynote Speakers',
    dayId: 'day3',
    description: 'A candid discussion about where software development is headed in the next 5 years.',
  },
];

export const attendees: Attendee[] = [
  {
    id: 'att1',
    name: 'Alex Kumar',
    role: 'Senior Engineer',
    company: 'Stripe',
    country: 'United States',
    interests: ['AI/ML', 'Payments'],
    isOnline: true,
    isSpeaker: false,
  },
  {
    id: 'att2',
    name: 'Maria Santos',
    role: 'Tech Lead',
    company: 'Nubank',
    country: 'Brazil',
    interests: ['Fintech', 'Microservices'],
    isOnline: true,
    isSpeaker: false,
  },
  {
    id: 'att3',
    name: 'James Wright',
    role: 'DevOps Engineer',
    company: 'Shopify',
    country: 'Canada',
    interests: ['Kubernetes', 'CI/CD'],
    isOnline: false,
    isSpeaker: false,
  },
  {
    id: 'att4',
    name: 'Sarah Chen',
    role: 'VP of Engineering',
    company: 'NeuralTech AI',
    country: 'United States',
    interests: ['AI/ML', 'Production Systems'],
    isOnline: true,
    isSpeaker: true,
  },
  {
    id: 'att5',
    name: 'Yuki Tanaka',
    role: 'Frontend Developer',
    company: 'LINE',
    country: 'Japan',
    interests: ['React', 'Web Performance'],
    isOnline: true,
    isSpeaker: false,
  },
  {
    id: 'att6',
    name: 'Fatima Al-Rashid',
    role: 'Security Architect',
    company: 'Saudi Aramco',
    country: 'Saudi Arabia',
    interests: ['Security', 'Zero Trust'],
    isOnline: true,
    isSpeaker: false,
  },
  {
    id: 'att7',
    name: 'Lucas Müller',
    role: 'Cloud Architect',
    company: 'SAP',
    country: 'Germany',
    interests: ['Cloud', 'Serverless'],
    isOnline: false,
    isSpeaker: false,
  },
  {
    id: 'att8',
    name: 'Priya Patel',
    role: 'Security Research Lead',
    company: 'CyberShield Labs',
    country: 'India',
    interests: ['Security', 'Threat Intelligence'],
    isOnline: true,
    isSpeaker: true,
  },
  {
    id: 'att9',
    name: 'Carlos Rivera',
    role: 'Mobile Engineer',
    company: 'Rappi',
    country: 'Colombia',
    interests: ['Mobile', 'React Native'],
    isOnline: true,
    isSpeaker: false,
  },
];
