import { Session, Speaker, AgendaDay, ChatMessage, Attendee } from '@/types';

export const speakers: Speaker[] = [
  {
    id: 'spk-1',
    name: 'Dr. Sarah Chen',
    title: 'VP of AI Research',
    company: 'DeepMind',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    bio: 'Dr. Sarah Chen leads AI safety research at DeepMind, with over 15 years of experience in machine learning and neural networks. She has published 80+ papers and holds 20 patents in AI.',
    topics: ['AI Safety', 'Neural Networks', 'ML Research'],
    sessionCount: 2,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'spk-2',
    name: 'Marcus Johnson',
    title: 'Principal Engineer',
    company: 'Vercel',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus',
    bio: 'Marcus is a core contributor to Next.js and leads the Edge Runtime team at Vercel. He is passionate about web performance and developer experience.',
    topics: ['Next.js', 'Edge Computing', 'Web Performance'],
    sessionCount: 1,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'spk-3',
    name: 'Priya Patel',
    title: 'CTO',
    company: 'CloudScale',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    bio: 'Priya built CloudScale from a 3-person startup to a $2B infrastructure company. She is an expert in distributed systems and cloud architecture.',
    topics: ['Cloud Architecture', 'Distributed Systems', 'Scaling'],
    sessionCount: 2,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'spk-4',
    name: 'Alex Rivera',
    title: 'Security Architect',
    company: 'Cloudflare',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    bio: 'Alex has spent 12 years protecting internet infrastructure at scale. At Cloudflare, he leads the Zero Trust security initiative and has helped secure thousands of enterprise customers.',
    topics: ['Zero Trust', 'DDoS Protection', 'Network Security'],
    sessionCount: 1,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'spk-5',
    name: 'Emma Williams',
    title: 'Head of Product',
    company: 'Linear',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma',
    bio: 'Emma has redefined how engineering teams think about project management. At Linear, she drives product strategy that has made it the tool of choice for 10,000+ engineering teams.',
    topics: ['Product Strategy', 'Developer Tools', 'Team Productivity'],
    sessionCount: 1,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'spk-6',
    name: 'James Kim',
    title: 'Staff Engineer',
    company: 'Stripe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=james',
    bio: 'James leads the payments infrastructure team at Stripe, processing billions of transactions annually. He is an expert in high-availability systems and financial technology.',
    topics: ['Payments', 'High Availability', 'FinTech'],
    sessionCount: 1,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'spk-7',
    name: 'Aisha Okonkwo',
    title: 'DevOps Lead',
    company: 'GitHub',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aisha',
    bio: 'Aisha champions DevOps culture at GitHub and has helped hundreds of organizations adopt CI/CD best practices. She is a frequent speaker and open source contributor.',
    topics: ['CI/CD', 'GitHub Actions', 'DevOps Culture'],
    sessionCount: 2,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'spk-8',
    name: 'David Park',
    title: 'Engineering Director',
    company: 'Figma',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    bio: 'David leads the collaborative editing infrastructure at Figma, enabling real-time collaboration for millions of designers. He is an expert in CRDTs and operational transformation.',
    topics: ['Real-time Collaboration', 'CRDTs', 'WebSockets'],
    sessionCount: 1,
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
  },
];

export const sessions: Session[] = [
  {
    id: 'ses-1',
    title: 'The Future of AI: From GPT-4 to AGI — What Developers Need to Know',
    description: 'An in-depth exploration of where AI is heading, the implications for software development, and how to build AI-native applications that will stand the test of time.',
    speaker: {
      id: 'spk-1',
      name: 'Dr. Sarah Chen',
      title: 'VP of AI Research',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    },
    track: 'AI & ML',
    level: 'Intermediate',
    duration: 60,
    time: '9:00 AM',
    attendeeCount: 4821,
    rating: 4.9,
    isLive: true,
    tags: ['AI', 'GPT', 'Machine Learning', 'Future Tech'],
  },
  {
    id: 'ses-2',
    title: 'Next.js 15 Deep Dive: Server Components, Streaming, and the Edge',
    description: 'Explore the latest features in Next.js 15 including improved server components, streaming SSR, and deploying to the edge for sub-50ms response times globally.',
    speaker: {
      id: 'spk-2',
      name: 'Marcus Johnson',
      title: 'Principal Engineer',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus',
    },
    track: 'Web Dev',
    level: 'Advanced',
    duration: 45,
    time: '10:30 AM',
    attendeeCount: 3654,
    rating: 4.8,
    isLive: false,
    tags: ['Next.js', 'React', 'Edge', 'Performance'],
  },
  {
    id: 'ses-3',
    title: 'Scaling to 100M Users: Architecture Lessons from the Trenches',
    description: 'Real-world lessons from scaling CloudScale from 0 to 100 million users. Covers database sharding, caching strategies, and the organizational changes required.',
    speaker: {
      id: 'spk-3',
      name: 'Priya Patel',
      title: 'CTO',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    },
    track: 'Cloud',
    level: 'Advanced',
    duration: 60,
    time: '11:00 AM',
    attendeeCount: 2987,
    rating: 4.9,
    isLive: false,
    tags: ['Scaling', 'Architecture', 'Cloud', 'Databases'],
  },
  {
    id: 'ses-4',
    title: 'Zero Trust Security: Protecting Modern Cloud Infrastructure',
    description: 'A practical guide to implementing Zero Trust architecture in your organization. Learn how to eliminate implicit trust and verify every request, every time.',
    speaker: {
      id: 'spk-4',
      name: 'Alex Rivera',
      title: 'Security Architect',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    },
    track: 'Security',
    level: 'Intermediate',
    duration: 45,
    time: '2:00 PM',
    attendeeCount: 2341,
    rating: 4.7,
    isLive: false,
    tags: ['Security', 'Zero Trust', 'Cloud', 'Identity'],
  },
  {
    id: 'ses-5',
    title: 'Building Products Engineers Love: Lessons from Linear',
    description: 'How Linear built a product that engineers actually want to use. Covers opinionated design, performance as a feature, and building for power users.',
    speaker: {
      id: 'spk-5',
      name: 'Emma Williams',
      title: 'Head of Product',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma',
    },
    track: 'Product',
    level: 'Beginner',
    duration: 40,
    time: '3:30 PM',
    attendeeCount: 1876,
    rating: 4.8,
    isLive: false,
    tags: ['Product', 'Design', 'Developer Tools', 'UX'],
  },
  {
    id: 'ses-6',
    title: 'GitHub Actions at Scale: CI/CD for Enterprise Teams',
    description: 'Learn how to design GitHub Actions workflows that scale to hundreds of repositories and thousands of daily runs without breaking the bank or your sanity.',
    speaker: {
      id: 'spk-7',
      name: 'Aisha Okonkwo',
      title: 'DevOps Lead',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aisha',
    },
    track: 'DevOps',
    level: 'Intermediate',
    duration: 50,
    time: '4:00 PM',
    attendeeCount: 2109,
    rating: 4.6,
    isLive: false,
    tags: ['GitHub Actions', 'CI/CD', 'DevOps', 'Automation'],
  },
  {
    id: 'ses-7',
    title: 'Real-Time Collaboration at Scale: How Figma Does It',
    description: 'A technical deep-dive into Figma\'s real-time collaboration engine. Learn about CRDTs, operational transformation, and building conflict-free collaborative experiences.',
    speaker: {
      id: 'spk-8',
      name: 'David Park',
      title: 'Engineering Director',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    },
    track: 'Web Dev',
    level: 'Advanced',
    duration: 55,
    time: '10:00 AM',
    attendeeCount: 1654,
    rating: 4.9,
    isLive: false,
    tags: ['WebSockets', 'CRDTs', 'Real-time', 'Collaboration'],
  },
  {
    id: 'ses-8',
    title: 'Engineering Leadership: From IC to Director in 3 Years',
    description: 'A candid conversation about the transition from individual contributor to engineering director. Covers the mindset shifts, common pitfalls, and how to build high-performing teams.',
    speaker: {
      id: 'spk-3',
      name: 'Priya Patel',
      title: 'CTO',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    },
    track: 'Leadership',
    level: 'Intermediate',
    duration: 45,
    time: '1:00 PM',
    attendeeCount: 2543,
    rating: 4.8,
    isLive: false,
    tags: ['Leadership', 'Career', 'Management', 'Teams'],
  },
];

export const agendaDays: AgendaDay[] = [
  {
    label: 'Day 1',
    date: 'June 10',
    items: [
      {
        id: 'ag-1',
        time: '8:30 AM',
        title: 'Registration & Virtual Lobby Opens',
        type: 'break',
        duration: 30,
        room: 'Main Lobby',
      },
      {
        id: 'ag-2',
        time: '9:00 AM',
        title: 'Opening Keynote: The State of Technology in 2024',
        speaker: 'Dr. Sarah Chen, DeepMind',
        type: 'keynote',
        description: 'Join us for an inspiring opening keynote that sets the stage for three days of learning, networking, and innovation. Dr. Sarah Chen will share her vision for the future of technology.',
        duration: 60,
        room: 'Main Stage',
        attendeeCount: 12000,
        isLive: true,
      },
      {
        id: 'ag-3',
        time: '10:30 AM',
        title: 'Break & Networking',
        type: 'break',
        duration: 30,
        room: 'Networking Lounge',
      },
      {
        id: 'ag-4',
        time: '11:00 AM',
        title: 'Next.js 15 Deep Dive: Server Components & Edge',
        speaker: 'Marcus Johnson, Vercel',
        type: 'session',
        description: 'A comprehensive look at the latest Next.js features and how to leverage them for maximum performance.',
        duration: 45,
        room: 'Track A — Web Dev',
        attendeeCount: 3654,
      },
      {
        id: 'ag-5',
        time: '11:00 AM',
        title: 'Scaling to 100M Users: Architecture Lessons',
        speaker: 'Priya Patel, CloudScale',
        type: 'session',
        description: 'Real-world lessons from scaling a startup to 100 million users.',
        duration: 60,
        room: 'Track B — Cloud',
        attendeeCount: 2987,
      },
      {
        id: 'ag-6',
        time: '12:30 PM',
        title: 'Lunch Break',
        type: 'break',
        duration: 60,
        room: 'Virtual Cafeteria',
      },
      {
        id: 'ag-7',
        time: '2:00 PM',
        title: 'Zero Trust Security: Protecting Modern Infrastructure',
        speaker: 'Alex Rivera, Cloudflare',
        type: 'session',
        description: 'Practical guide to implementing Zero Trust in your organization.',
        duration: 45,
        room: 'Track C — Security',
        attendeeCount: 2341,
      },
      {
        id: 'ag-8',
        time: '3:30 PM',
        title: 'Panel: The Future of Remote Engineering Teams',
        speaker: 'Multiple Speakers',
        type: 'panel',
        description: 'Industry leaders discuss the evolving landscape of remote work, async communication, and building culture across time zones.',
        duration: 60,
        room: 'Main Stage',
        attendeeCount: 5200,
      },
      {
        id: 'ag-9',
        time: '5:00 PM',
        title: 'Day 1 Wrap-up & Virtual Happy Hour',
        type: 'break',
        duration: 60,
        room: 'Networking Lounge',
      },
    ],
  },
  {
    label: 'Day 2',
    date: 'June 11',
    items: [
      {
        id: 'ag-10',
        time: '9:00 AM',
        title: 'Day 2 Keynote: AI-Native Development',
        speaker: 'Dr. Sarah Chen, DeepMind',
        type: 'keynote',
        description: 'How AI is fundamentally changing how we write, test, and deploy software.',
        duration: 60,
        room: 'Main Stage',
        attendeeCount: 11500,
        isLive: true,
      },
      {
        id: 'ag-11',
        time: '10:30 AM',
        title: 'Workshop: Building Your First LLM-Powered App',
        speaker: 'Dr. Sarah Chen, DeepMind',
        type: 'workshop',
        description: 'Hands-on workshop where you will build a production-ready LLM application from scratch.',
        duration: 90,
        room: 'Workshop Room 1',
        attendeeCount: 800,
      },
      {
        id: 'ag-12',
        time: '1:00 PM',
        title: 'Engineering Leadership: IC to Director',
        speaker: 'Priya Patel, CloudScale',
        type: 'session',
        description: 'Career growth strategies for senior engineers looking to move into leadership.',
        duration: 45,
        room: 'Track D — Leadership',
        attendeeCount: 2543,
      },
      {
        id: 'ag-13',
        time: '3:00 PM',
        title: 'GitHub Actions at Scale',
        speaker: 'Aisha Okonkwo, GitHub',
        type: 'session',
        description: 'CI/CD best practices for enterprise-scale teams.',
        duration: 50,
        room: 'Track E — DevOps',
        attendeeCount: 2109,
      },
    ],
  },
  {
    label: 'Day 3',
    date: 'June 12',
    items: [
      {
        id: 'ag-14',
        time: '9:00 AM',
        title: 'Closing Keynote: Building the Future Together',
        speaker: 'Multiple Speakers',
        type: 'keynote',
        description: 'A forward-looking keynote bringing together all the themes from TechSummit 2024.',
        duration: 90,
        room: 'Main Stage',
        attendeeCount: 12000,
      },
      {
        id: 'ag-15',
        time: '11:00 AM',
        title: 'Real-Time Collaboration at Scale: Figma\'s Approach',
        speaker: 'David Park, Figma',
        type: 'session',
        description: 'Technical deep-dive into building collaborative real-time applications.',
        duration: 55,
        room: 'Track A — Web Dev',
        attendeeCount: 1654,
      },
      {
        id: 'ag-16',
        time: '2:00 PM',
        title: 'Closing Networking & Awards Ceremony',
        type: 'break',
        duration: 120,
        room: 'Main Stage',
      },
    ],
  },
];

export const chatMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    user: {
      name: 'TechSummit Host',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=host',
      isHost: true,
    },
    content: 'Welcome to TechSummit 2024! 🎉 We are live! Feel free to ask questions and connect with fellow attendees.',
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    reactions: ['🎉', '👏'],
  },
  {
    id: 'msg-2',
    user: {
      name: 'Jordan Lee',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jordan',
      isHost: false,
    },
    content: 'Super excited for Dr. Chen\'s keynote! Her work on AI safety is groundbreaking.',
    timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    reactions: ['👍'],
  },
  {
    id: 'msg-3',
    user: {
      name: 'Samantha Wu',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=samantha',
      isHost: false,
    },
    content: 'Joining from Singapore! Anyone else here from Southeast Asia?',
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    reactions: [],
  },
  {
    id: 'msg-4',
    user: {
      name: 'TechSummit Host',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=host',
      isHost: true,
    },
    content: 'We have attendees from 90 countries today! Use the Networking Lounge to connect with people near you.',
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    reactions: ['🌍', '❤️'],
  },
  {
    id: 'msg-5',
    user: {
      name: 'Raj Sharma',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=raj',
      isHost: false,
    },
    content: 'The Next.js session is going to be 🔥 Marcus always delivers incredible content.',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    reactions: ['🔥'],
  },
  {
    id: 'msg-6',
    user: {
      name: 'Maria Garcia',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=maria',
      isHost: false,
    },
    content: 'Quick question for the host: will all sessions be recorded and available after the event?',
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    reactions: [],
  },
  {
    id: 'msg-7',
    user: {
      name: 'TechSummit Host',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=host',
      isHost: true,
    },
    content: 'Yes @Maria! All sessions will be available for 90 days after the event for all registered attendees.',
    timestamp: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    reactions: ['👍', '🙌'],
  },
];

export const attendees: Attendee[] = [
  {
    id: 'att-1',
    name: 'Jordan Lee',
    title: 'Senior Software Engineer',
    company: 'Shopify',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jordan',
    location: 'Toronto, Canada',
    interests: ['React', 'TypeScript', 'GraphQL'],
    isOnline: true,
  },
  {
    id: 'att-2',
    name: 'Samantha Wu',
    title: 'ML Engineer',
    company: 'ByteDance',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=samantha',
    location: 'Singapore',
    interests: ['AI/ML', 'Python', 'Data Science'],
    isOnline: true,
  },
  {
    id: 'att-3',
    name: 'Raj Sharma',
    title: 'DevOps Engineer',
    company: 'Atlassian',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=raj',
    location: 'Sydney, Australia',
    interests: ['Kubernetes', 'Terraform', 'CI/CD'],
    isOnline: true,
  },
  {
    id: 'att-4',
    name: 'Maria Garcia',
    title: 'Product Manager',
    company: 'Notion',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=maria',
    location: 'Madrid, Spain',
    interests: ['Product Strategy', 'UX', 'Analytics'],
    isOnline: false,
  },
  {
    id: 'att-5',
    name: 'Kwame Asante',
    title: 'Full Stack Developer',
    company: 'Andela',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kwame',
    location: 'Accra, Ghana',
    interests: ['Node.js', 'React', 'PostgreSQL'],
    isOnline: true,
  },
  {
    id: 'att-6',
    name: 'Yuki Tanaka',
    title: 'iOS Engineer',
    company: 'Mercari',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=yuki',
    location: 'Tokyo, Japan',
    interests: ['Swift', 'SwiftUI', 'Mobile'],
    isOnline: true,
  },
  {
    id: 'att-7',
    name: 'Fatima Al-Hassan',
    title: 'Security Engineer',
    company: 'Aramco Digital',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatima',
    location: 'Riyadh, Saudi Arabia',
    interests: ['Cybersecurity', 'Penetration Testing', 'Cloud Security'],
    isOnline: false,
  },
  {
    id: 'att-8',
    name: 'Lucas Oliveira',
    title: 'Backend Engineer',
    company: 'Nubank',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lucas',
    location: 'São Paulo, Brazil',
    interests: ['Kotlin', 'Microservices', 'FinTech'],
    isOnline: true,
  },
];
